### ISSUE TITLE
The `role` property in `sync`

### ISSUE THREAD

**Issue by iherman** [w3c/sync-media-pub#38]
[§3.3.1](https://w3c.github.io/sync-media-pub/sync-media.html#structural-semantics) introduces the `role` property. However, it is misleading, and it should be defined as `sync:role`; the same holds to its specification in the table of §3.3.2. [Example 2](https://w3c.github.io/sync-media-pub/sync-media.html#example-2-using-role-to-mark-a-page-number) actually gets it right, but it is very unclear to the reader which one is correct.

B.t.w., a similar comment can be made for the introduction of the `track` element in [§3.5](https://w3c.github.io/sync-media-pub/sync-media.html#tracks).

**Comment by marisademeglio** [comment]
The story here is that the CG told me they would like to define the model first before moving onto serialization format(s). 

Therefore, I tried to do a weird balancing act to keep the model definition generic and easily suited to both JSON and XML (so: no namespaces, use words like "node" and "property" instead of "element" and "attribute"), but of course for the examples, a format was required.

I do not know how long to wait for the CG to give feedback about the model before just making a decision myself on what to do. I don't think I should hold my breath here...
